### ISSUE TITLE
HILT : lateinit property repository has not been initialized in ViewModel

### ISSUE THREAD

**Issue by thizisarun** [davidliu/DaggerHiltExploration#4]
I follow your example but i encountered "lateinit property repository has not been initialized in ViewModel". How can i resolve this error.

Error Link : https://stackoverflow.com/questions/62826677/hilt-lateinit-property-repository-has-not-been-initialized-in-viewmodel

**Comment by davidliu** [comment]
Posted an answer on the stackoverflow post.
